### PR TITLE
Create all schemas (Issue #3)

### PR DESCRIPTION
**Pull request by nidi3**

### CODE REVIEW

**Comment by mrix** [comment]
@nidi3 Why do you need this new method? You can use multiple `createSchema` calls instead.

**Comment by nidi3** [comment]
The use case is to generate schemas for all types in a project. How can I achieve this without knowing the types a priori?

**Comment by mrix** [comment]
@nidi3 As I understand, you're using this package as a library, and not as CLI. Am I right?
So you could implement you own "function findAllTypes(program: ts.Program): string[]" and then process the found types with `SchemaGenerator`.

Please don't get me wrong. Your PR has an excellent quality but I really want to keep this tool as simple as possible. I hope this project's code is enough structured and extendable to integrate it with your  projects ;-)

**Comment by nidi3** [comment]
Yes, I want to use it for [apikana](https://github.com/nidi3/apikana).
Thanks for the clarification, it's very nice code and I think it should be no problem integrating it.

**Pull request closed without merging**
